import { config } from '@vue/test-utils';
import { vi } from 'vitest';

vi.mock('@/styles/theme.css', () => ({}));
vi.mock('@/components/LegalModal.vue', () => ({ default: { template: '<div />' } }));

vi.mock('axios', () => {
  const mockAxios = {
    create: vi.fn(() => mockAxios),
    get: vi.fn(),
    post: vi.fn(),
    patch: vi.fn(),
    delete: vi.fn(),
    interceptors: {
      request: { use: vi.fn() },
      response: { use: vi.fn() },
    },
    defaults: {
      baseURL: '',
      withCredentials: false,
      headers: {},
    },
  };
  return { default: mockAxios, ...mockAxios };
});

config.global.stubs = {
  RouterLink: true,
  RouterView: true,
  VApp: true,
  VLayout: true,
  VMain: true,
  VNavigationDrawer: true,
  VAppBar: true,
  VList: true,
  VListItem: true,
  VIcon: true,
  VBtn: true,
  VCard: true,
  VTextField: true,
  VSelect: true,
  VForm: true,
  VAlert: true,
  VProgressLinear: true,
  VChip: true,
  VDialog: true,
  VMenu: true,
  VBottomNavigation: true,
  VFooter: true,
  VDivider: true,
  VTabs: true,
  VTab: true,
  VWindow: true,
  VWindowItem: true,
  VSlideGroup: true,
  VSlideItem: true,
  VRow: true,
  VCol: true,
  VSpacer: true,
  VToolbar: true,
  VToolbarTitle: true,
  VContainer: true,
  VBadge: true,
  VAvatar: true,
  VTable: true,
  VDataTable: true,
  VDataTableServer: true,
  VPagination: true,
  VTooltip: true,
  VOverlay: true,
  VSheet: true,
  VExpansionPanel: true,
  VExpansionPanels: true,
  VExpansionPanelTitle: true,
  VExpansionPanelText: true,
  VCardTitle: true,
  VCardText: true,
  VCardActions: true,
  VListItemTitle: true,
  VListItemSubtitle: true,
  VListItemAction: true,
  VListItemContent: true,
  VSwitch: true,
  VTextarea: true,
  VRadioGroup: true,
  VRadio: true,
  VCheckbox: true,
  VCombobox: true,
  VAutocomplete: true,
  VFileInput: true,
  VSlider: true,
  VRangeSlider: true,
  VRating: true,
  VTimeline: true,
  VTimelineItem: true,
  VTreeview: true,
  VDatePicker: true,
  VTimePicker: true,
  VColorPicker: true,
  VStepper: true,
  VStepperStep: true,
  VStepperContent: true,
  VSpeedDial: true,
  VParallax: true,
  VImg: true,
  VLazy: true,
  VResponsive: true,
  VHover: true,
  VCounter: true,
  VBanner: true,
  VAppBarNavIcon: true,
  VAppBarTitle: true,
  VSystemBar: true,
  VNavigationDrawerLocation: true,
  VListGroup: true,
  VListSubheader: true,
  VListItemMedia: true,
  VListItemGroup: true,
  VSimpleTable: true,
  VVirtualScroll: true,
  VItemGroup: true,
  VItem: true,
  VSheetFoo: true,
  VCode: true,
  VProgressCircular: true,
  VLocaleProvider: true,
  VDatePicker: true,
  VCardActions: true,
};
